application: laporpresiden7
version: 20
runtime: php55
api_version: 1

instance_class: B3
basic_scaling:
  max_instances: 1
  idle_timeout: 25s

handlers:  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /(.+\.(css))$
  static_files: \1
  upload: .+\.(css)$
  
- url: /(.+\.(js))$
  static_files: \1
  upload: .+\.(js)$

# Serve php scripts.
- url: /.*
  script: mod_rewrite.php
