application: laporpresiden-prod
version: 30
runtime: php55
api_version: 1

instance_class: B4

basic_scaling:
  max_instances: 2
  idle_timeout: 30s

handlers:  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /(.+\.(css))$
  static_files: \1
  upload: .+\.(css)$
  
- url: /(.+\.(js))$
  static_files: \1
  upload: .+\.(js)$

- url: /(.+\.(html))$
  static_files: \1
  upload: .+\.(html)$

# Serve php scripts.
- url: /.*
  script: mod_rewrite.php
